org: nspehler
app: nspehler
service: nspehler

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: eu-west-1
  memorySize: 256
  timeout: 29
  environment:
    DB_URL: ${param:DB_URL}
  layers:
    - arn:aws:lambda:eu-west-1:035114897561:layer:nspehler:3

functions:
  AirbnbMonitoring:
    handler: airbnb/monitoring/lambda_function.lambda_handler
    name: ${self:service}-${self:provider.stage}-airbnb-monitoring
    description: Monitor new Airbnb listings
    timeout: 240
    environment:
      AIRBNB_API_KEY: ${param:AIRBNB_API_KEY}
      AIRBNB_SHA256_HASH: ${param:AIRBNB_SHA256_HASH}
      SCRAPINGBEE_API_KEY: ${param:SCRAPINGBEE_API_KEY}
    # events:
    #   - schedule:
    #       rate: rate(12 hours)

package:
  exclude:
    - layer/**
    - package.json
    - bun.lockb
