service: nspehler

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: eu-west-1
  memorySize: 256
  timeout: 29
  environment: ${ssm:/aws/reference/secretsmanager/nspehler/prod}
  layers:
    - arn:aws:lambda:eu-west-1:035114897561:layer:nspehler:3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: arn:aws:secretsmanager:${self:provider.region}:*:secret:nspehler/prod-*

functions:
  AirbnbMonitoring:
    handler: airbnb/monitoring/lambda_function.lambda_handler
    name: ${self:service}-${self:provider.stage}-airbnb-monitoring
    description: Monitor new Airbnb listings
    timeout: 240
    # events:
    #   - schedule:
    #       rate: rate(12 hours)
  DomainNameMonitoring:
    handler: domain_name/monitoring/lambda_function.lambda_handler
    name: ${self:service}-${self:provider.stage}-domain-name-monitoring
    description: Monitor availability of domain names
    timeout: 30
    # events:
    #   - schedule:
    #       rate: rate(5 minutes)
  FrankOceanMonitoring:
    handler: frank_ocean/monitoring/lambda_function.lambda_handler
    name: ${self:service}-${self:provider.stage}-frank-ocean-monitoring
    description: Monitor Frank Ocean Channel Orange product availability
    timeout: 30
    events:
      - schedule:
          rate: rate(1 minute)
  PosIndonesiaMonitoring:
    handler: pos_indonesia/monitoring/lambda_function.lambda_handler
    name: ${self:service}-${self:provider.stage}-pos-indonesia-monitoring
    description: Monitor POS Indonesia package tracking status
    timeout: 30
    events:
      - schedule:
          rate: rate(5 minutes)
  ShopifyMonitoring:
    handler: shopify/monitoring/lambda_function.lambda_handler
    name: ${self:service}-${self:provider.stage}-shopify-monitoring
    description: Monitor Shopify stores for new releases
    timeout: 120
    events:
      - schedule:
          rate: rate(5 minutes)
  RayeMonitoring:
    handler: raye/monitoring/lambda_function.lambda_handler
    name: ${self:service}-${self:provider.stage}-raye-monitoring
    description: Monitor RAYE product availability
    timeout: 30
    # events:
    #   - schedule:
    #       rate: rate(5 minutes)

package:
  exclude:
    - layer/**
    - package.json
    - bun.lockb
